---
default:
        cmd: | #!/usr/bin/env bash


                clear

                cd ~/repositories/iMessage_bot

                go build
                ./iMessage_bot -file=file.csv -message=sup NAME

